config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :registrations => :registrations }
  require "sidekiq/web"
        authenticate :user, ->(user) { user.admin? } do
        mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'
  get "email", to: 'user_mailer#new_notification'
  get "dashboard", to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about_us', to: 'pages#about_us'
  resources :plants
  resources :pets do
    resources :pet_categories do
      resources :pet_notifications
    end
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :pet_categories
  has_many :categories, through: :pet_categories
  has_many :pet_notifications, through: :pet_categories

  SPECIES = %w[cat dog]
  SPECIES_FILTER = SPECIES.map do |species|
                        [species.capitalize, species]
                      end
  DOG_BREED = []

  dog_url = 'https://api.thedogapi.com/v1/breeds'
  dog_breeds_string = RestClient.get(dog_url).body
  dog_breeds = JSON.parse(dog_breeds_string)

  dog_breeds.map do |dog|
    DOG_BREED << dog["name"]
  end

  CAT_BREED = []

  cat_url = 'https://api.thecatapi.com/v1/breeds'
  cat_breeds_string = RestClient.get(cat_url).body
  cat_breeds = JSON.parse(cat_breeds_string)

  cat_breeds.map do |cat|
    CAT_BREED << cat["name"]
  end

  CAT_AND_DOG_BREED = []
  cat_breeds.map do |cat|
    CAT_AND_DOG_BREED << cat["name"]
  end
  dog_breeds.map do |dog|
    CAT_AND_DOG_BREED << dog["name"]
  end

  validates :name, presence: true
  validates :breed, inclusion: { in: CAT_AND_DOG_BREED }
  validates :species, inclusion: { in: SPECIES }
  validates :birthdate, presence: true
  has_one_attached :image
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
    authorize @pet
    if @pet.species == "dog"
      response = JSON.parse(RestClient.get(dog_url(@pet.breed)))
      @description = response[0]["temperament"]
    else
      response = JSON.parse(RestClient.get(cat_url(@pet.breed)))
      @description = response[0]["description"]
    end
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    authorize @pet
    @pet.user = current_user

    if @pet.save

      redirect_to new_pet_pet_category_path(@pet)
    else
      render :new
    end
  end

  def update
    @pet.update(pet_params)
    redirect_to new_pet_pet_category_path(@pet)
  end

  def edit
  end

  def destroy
  end

  private

  def set_task
    @pet = Pet.find(params[:id])
    authorize @pet
  end

  def pet_params
    params.require(:pet).permit(:name, :breed, :weight, :birthdate, :species, :image)
  end

  def dog_url(id)
    "https://api.thedogapi.com/v1/breeds/search?q=#{id}"
  end

  def cat_url(id)
    "https://api.thecatapi.com/v1/breeds/search?q=#{id}"
  end
end

app/views/pets/destroy.html.erb
<h1>Pets#destroy</h1>
<p>Find me in app/views/pets/destroy.html.erb</p>

app/views/pets/edit.html.erb
<div class="container justify-center">
  <div class="form">
  <div class="d-flex justify-content-center p-4">
    <h2>Update info</h2>
  </div>

  <div class="input">
    <%= simple_form_for (@pet) do |p| %>
    <%= p.input :name, placeholder: 'Name' %>
    <%= p.input :species, collection: Pet::SPECIES_FILTER, selected: 'Cat' %>
    <%= p.input :breed, placeholder: 'Breed', collection: Pet::DOG_BREED, input_html: { id: :dog_breeds, class: "pet_selection" } %>
    <%= p.input :breed, placeholder: 'Breed', label: false, collection: Pet::CAT_BREED, input_html: { id: :cat_breeds } %>
    <%= p.input :birthdate, as: :date, placeholder: 'Birthdate' %>
    <%= p.input :weight, as: :integer, placeholder: 'Kg' %>
    <%= p.input :image, as: :file, required: false %>

      <div class="form-actions">
        <div class="row justify-content-center">
          <div class="col-2 d-flex justify-content-center">
            <%= p.submit 'Add this pet 🐶', class: "button-form" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<h1>Pets#index</h1>
<p>Find me in app/views/pets/index.html.erb</p>

app/views/pets/new.html.erb
<div class="container justify-center">
  <div class="form">
  <div class="d-flex justify-content-center p-4">
    <h2>New Pet</h2>
  </div>

  <div class="input">
    <%= simple_form_for (@pet) do |p| %>
    <%= p.input :name, placeholder: 'Name' %>
    <%= p.input :species, collection: Pet::SPECIES_FILTER, selected: 'Cat' %>
    <%= p.input :breed, placeholder: 'Breed', collection: Pet::CAT_AND_DOG_BREED %>
  <!--   p.input :breed, placeholder: 'Breed', label: false, collection: Pet::CAT_BREED, input_html: { id: :cat_breeds } %> -->
    <%= p.input :birthdate, as: :date, placeholder: 'Birthdate' %>
    <%= p.input :weight, as: :integer, placeholder: 'Kg' %>
    <%= p.input :image, as: :file, required: false %>

      <div class="form-actions">
        <div class="row justify-content-center">
          <div class="col-2 d-flex justify-content-center">
            <%= p.submit 'Add this pet 🐶', class: "button-form" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<h2 class="mb-4"><strong>Your pet's profile</strong></h2>
<div>
  <% if @pet.image.attached? %>
    <%= cl_image_tag @pet.image.key, class: "show-img" %>
  <% end %>
</div>

<div class="show-main-card d-flex justify-content-between">
      <div class="id">
        <h1><strong> <%= @pet.name.capitalize %></strong></h1>
        <h3><%= @pet.breed %></h3>
        <h4 style="color: #809C53"><strong>Alive</strong></h4>
      </div>
        <div class="d-flex flex-column align-items-end justify-content-between">
          <div class="p-2"><%= link_to edit_pet_path(@pet) do %>
            <i class="far fa-bell big" style="font-size: 1.2rem;"></i>
            <% end %>
          </div>
          <div class="d-flex align-items-end flex-column">
             <h5 style="color: #A5A5A5"><i class="fas fa-weight"></i> <%= @pet.weight %> kg</h5>
             <h5 style="color: #A5A5A5"> <i class="fas fa-birthday-cake"></i> <%= @pet.birthdate %></h5>
          </div>
      </div>
    </div>

<h3 class="mt-4"><strong>Breed description</strong></h3>

<% dog_url = "https://api.thedogapi.com/v1/breeds/search?q=#{@pet.breed}" %>
<% dog_breeds_string = RestClient.get(dog_url).body  %>
<% dog = JSON.parse(dog_breeds_string) %>

<% cat_url = "https://api.thecatapi.com/v1/breeds/search?q=#{@pet.breed}" %>
<% cat_breeds_string = RestClient.get(cat_url).body %>
<% cat = JSON.parse(cat_breeds_string) %>

<div class="row">
  <div class="col-6 nopaddinga">
    <% if dog == [] %>
       <img class="img-breed" src=<%= "https://cdn2.thecatapi.com/images/#{cat[0]["reference_image_id"]}.jpg" %> />
    <% else %>
       <img class="img-breed" src=<%= "https://cdn2.thedogapi.com/images/#{dog[0]["reference_image_id"]}.jpg" %> />
    <% end %>
  </div>
  <div class="col-6 nopaddingb">
    <div class="breed-card">
      <div class="breed-content"> <%= @description %> </div>
    </div>
  </div>
</div>

<% content_for :meta_title, "#{@pet.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @description %>
<% if @pet.image.attached? %>
<% content_for :meta_image, (cl_image_tag @pet.image.key) %>
<% end %>

app/views/pets/update.html.erb
<h1>Pets#update</h1>
<p>Find me in app/views/pets/update.html.erb</p>