config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :registrations => :registrations }
  require "sidekiq/web"
        authenticate :user, ->(user) { user.admin? } do
        mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'
  get "email", to: 'user_mailer#new_notification'
  get "dashboard", to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about_us', to: 'pages#about_us'
  resources :plants
  resources :pets do
    resources :pet_categories do
      resources :pet_notifications
    end
  end
end

app/views/partials/_animated_dog.html.erb
<div class="dog">
  <div class="head">
    <div class="ears"></div>
    <div class="eyes"></div>
    <div class="beard">
      <div class="mouth">
        <div class="tongue"></div>
      </div>
    </div>
  </div>
  <div class="belt"></div>
  <div class="stomach"></div>
  <div class="legs">
    <div class="left"></div>
    <div class="right"></div>
  </div>
  <div class="tail"></div>
</div>

app/views/partials/_animated_plant.html.erb
<div class="plant-wrap">
  <div class="plant-base">
    <div class="flowerpot"></div>
    <div class="blade blade-center"></div>
    <div class="blade blade-left-s"></div>
    <div class="blade blade-right-s"></div>
    <div class="blade blade-left-l"></div>
    <div class="blade blade-right-l"></div>
  </div>
</div>

app/views/partials/_buttons.html.erb
<div class="pb-3">
  <h5>Want new responsibilities?</h5>
</div>
<div class="row">
  <div class="col-6">
    <%= link_to new_plant_path do %>
    <div class="add-a-button" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1567871318107-054c098e6b59?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=844&q=80)">
      Add a plant
    </div>
    <% end  %>
  </div>

  <div class="col-6">
    <%= link_to new_pet_path do %>
    <div class="add-a-button" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1415369629372-26f2fe60c467?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80)">
      Add a pet
    </div>
    <% end  %>
    </div>
  </div>

app/views/partials/_carousel.html.erb
<div class="carousel-container">
  <h2 class="carousel-title">You forgot. Again.</h2>

  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "01.jpg", alt: "Dog", class: "d-block w-100" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "02.jpg", alt: "Dog", class: "d-block w-100" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "03.jpg", alt: "Dog", class: "d-block w-100" %>
      </div>
    </div>
  </div>
</div>
<div class="below-hero">
  <div class="content-hero row">
    <div class="col-8">
      <h3>A new way of being on top of your pets and plants</h3>
      <p>We know they mean the world to you but sometimes you can forget. So dodge that feeling of impending doom with us!</p>
      <%= link_to 'Start now!', new_user_registration_path, class: 'btn' %>
    </div>
    <div class="col-4">
      <%= image_tag "04.jpg", alt: "Person walking dog", class: "hero-image" %>
    </div>
  </div>
</div>

app/views/partials/_featured.html.erb
<div class="pt-4 pb-3">
  <h5>Featured breeds</h5>
</div>

  <% dog_url = 'https://api.thedogapi.com/v1/breeds' %>
  <% dog_breeds_string = RestClient.get(dog_url).body  %>
  <% dog_breeds = JSON.parse(dog_breeds_string) %>
  <% dog = dog_breeds.sample %>
  <% dog_image_link = dog["image"]["url"] %>

  <% cat_url = 'https://api.thecatapi.com/v1/breeds' %>
  <% cat_breeds_string = RestClient.get(cat_url).body  %>
  <% cat_breeds = JSON.parse(cat_breeds_string) %>
  <% cat = cat_breeds.sample %>
  <% cat_image_link = cat["image"]["url"] %>

<div class="row">

<div class="col-6">
  <div class="card-trip">
    <img src=<%= dog_image_link %> />
    <div class="card-trip-infos">
      <h6 style="font-size: 1.5rem"> <%= dog["name"] %></h6>
       <p><%= dog["temperament"] %></p>
    </div>
  </div>
</div>

<div class="col-6">
  <div class="card-trip">
    <img src=<%= cat_image_link %> />
    <div class="card-trip-infos">
      <h6 style="font-size: 1.5rem"> <%= cat["name"] %></h6>
       <p><%= cat["description"] %></p>
    </div>
  </div>
</div>
</div>

app/views/partials/_homepage_banner.html.erb
<div id="main-banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(<%= asset_path 'background.png' %>); background-size: cover; background-position: center center;">
  <h1 id="main-title">
    <p>A new way of reminding you to care for</p>
    <span id="banner-typed-text"></span>
  </h1>
  <%= link_to 'Start now!', new_user_registration_path, id: 'main-btn', class: 'btn' %>

  <div class="cat-and-plant d-flex justify-content-center align-items-end">
      <%= render './partials/animated_plant' %>
      <%= render './partials/animated_dog' %>
  </div>
</div>

app/views/partials/_pawsbackground.html.erb
 <div class="walking_paws">
    <div class="paw-print-1 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-2 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-3 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-4 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-5 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-6 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-7 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>

    <div class="paw-print-8 paws">
      <div class="pad large"></div>
      <div class="pad small-1"></div>
      <div class="pad small-2"></div>
      <div class="pad small-3"></div>
      <div class="pad small-4"></div>
    </div>
  </div>

app/views/partials/_running_dog.html.erb
<div class="running_dog m-5"></div>

app/views/partials/_welcome_back.html.erb
<div class="pl-2">
  <h2><strong>Welcome back, <%= current_user.name.capitalize %>!</strong></h2>
  <h5>Here are your latest additions</h5>
</div>
<div class="cards">
    <% if current_user.pets.empty? %>
        <%= "You have no pets yet!" %>
    <% else %>

        <% current_user.pets.last(1).each do |p| %>
            <%= link_to pet_path(p) do %>
                  <div class="card">
                    <div class="row">
                      <div class="col-8">
                        <% if p.image.attached? %>
                          <%= cl_image_tag p.image.key %>
                        <% else %>
                          <%= "No image" %>
                        <% end %>
                      </div>
                      <div class="col-4">
                        <div class="h-100 d-flex justify-content-between flex-column">
                          <div class="d-flex justify-content-between">
                            <div class="icons pt-4">
                              <div class="pr-2"><i class="fas fa-utensils"></i></div>
                              <div class="pr-2"><i class="fas fa-briefcase-medical"></i></div>
                              <div class="pr-2"><i class="fas fa-soap"></i></div>
                            </div>
                            <div class="icons pt-4 pr-4">

                                <i class="far fa-bell"></i>

                            </div>
                          </div>
                          <div class="name-and-breed pb-4">
                              <h3><strong><%= p.name %></strong></h3>
                              <h6 style="font-size: 1.2rem;"> <%= p.breed %> </h6>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
            <% end %>
    <% end %>
  <% end %>


    <% if current_user.plants.empty? %>
        <%= "You have no plants yet!" %>
    <% else %>
    <% current_user.plants.last(1).each do |p| %>
    <%= link_to plant_path(p) do %>
            <div class="card">
                    <div class="row">
                      <div class="col-8">
                          <% if p.image.attached? %>
                            <%= cl_image_tag p.image.key %>
                          <% else %>
                            <%= "No image" %>
                          <% end %>
            </div>
            <div class="col-4">
                <div class="h-100 d-flex justify-content-between flex-column">
                  <div class="d-flex justify-content-between">
                    <div class="icons pt-4">
                      <i class="fas fa-tint"></i>
                    </div>
                      <div class="icons pt-4 pr-4">

                        <i class="far fa-bell"></i>

                    </div>
                  </div>
                <div class="name-and-breed pb-4">
                  <h3><strong> <%= p.nickname %></strong></h3>
                  <h6 style="font-size: 1.2rem;"> <%= p.species %></h6>
                </div>
                        </div>
                      </div>
                    </div>
                  </div>
            <% end %>
    <% end %>
  <% end %>
  </div>