config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :registrations => :registrations }
  require "sidekiq/web"
        authenticate :user, ->(user) { user.admin? } do
        mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'
  get "email", to: 'user_mailer#new_notification'
  get "dashboard", to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about_us', to: 'pages#about_us'
  resources :plants
  resources :pets do
    resources :pet_categories do
      resources :pet_notifications
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="one">
  <div class="footer">
    <div class="d-flex justify-content-center">
      <%= link_to 'Home', root_path, class: "footer-links" %>
      <%= link_to 'About Us', about_us_path, class: "footer-links" %>
      <%= mail_to "info@doomdodger.me", "Contact Us", class: "footer-links"  %>
      <%= link_to 'Privacy Policy', about_us_path, class: "footer-links" %>
      <%= link_to 'Cookies Policy', about_us_path, class: "footer-links" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="site-header">
  <div class="wrapper site-header__wrapper">
      <nav class="nav">
        <button class="nav__toggle btn-green" aria-expanded="false" type="button">
            <% if user_signed_in? %>
              <i class="fas fa-plus"></i>
            <% else %>
              <i class="fas fa-user"></i>
            <% end %>
        </button>
          <ul class="nav__wrapper">
            <% if user_signed_in? %>

              <li class="nav__item"><%= link_to 'Pet', new_pet_path %></li>
              <li class="nav__item"><%= link_to 'Plant', new_plant_path %></li>
            <% else %>
              <li class="nav__item"><%= link_to 'Sign in', user_session_path %></li>
              <li class="nav__item"><%= link_to 'Register', new_user_registration_path %></li>
            <% end %>
          </ul>
      </nav>
    <div class="d-flex align-items-center">
      <a class="navbar-brand" href="/">
        <%= image_tag "Logo.png" %>
      </a>
    </div>
                <div class="navatar">
                <% if user_signed_in? %>
                  <%= link_to dashboard_path do %>
                  <% if user_signed_in? %>
                      <% if current_user.avatar.attached?%>
                        <div class="profile">
                          <%= cl_image_tag current_user.avatar.key %>
                          <h6 class="nav__dashboard" style="color: white"><strong>Dashboard</strong></h6>
                        </div>
                      <% else %>
                        <div class="profile"><%= image_tag "https://via.placeholder.com/350x150" %></div>
                      <% end %>
                  <% else %>
                    <div class="profile">
                      <h6 class="nav__dashboard" style="color: white"><strong><%= link_to 'Register', new_user_registration_path %></strong></h6>
                    </div>
                  <% end %>
              <% end %>
              <% end %>
              </div>

</header>