config/routes.rb
Rails.application.routes.draw do
devise_for :users, :controllers => { :registrations => :registrations }
  require "sidekiq/web"
        authenticate :user, ->(user) { user.admin? } do
        mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'
  get "email", to: 'user_mailer#new_notification'
  get "dashboard", to: 'pages#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'about_us', to: 'pages#about_us'
  resources :plants
  resources :pets do
    resources :pet_categories do
      resources :pet_notifications
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  after_create :send_notification

  def send_notification
    notification = NewNotification.with(plant: self.id)
    notification.deliver(self.user)
  end

  SPECIES_FILTER = []

  plant_file = File.read('./app/assets/plantdb/data.json')
  plants = JSON.parse(plant_file)
  plants["alphabetList"]["glossaryItems"].each do |element|
    SPECIES_FILTER << element["primaryName"]
  end

  def self.water_reminder
    reminders = Plant.all
    reminders.each do |reminder|
      notification = PlantNotification.with(plant: reminder.id)
      notification.deliver(reminder.plant.user)
    end
  end

  validates :species, presence: true
  validates :nickname, presence: true
  validates :species, inclusion: { in: SPECIES_FILTER }
  has_one_attached :image
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update]

  def index
    @plants = Plant.all
  end

  def show
    authorize @plant
  end

  def new
    @plant = Plant.new
    authorize @plant
  end

  def create
    @plant = Plant.new(plant_params)
    @user = current_user
    @plant.user = @user
    authorize @plant
    if @plant.save!
      redirect_to @plant, notice: 'your plant has been added!'
    else
      render :new
    end
    authorize @plant
  end

  def edit
  end

  def update
    @plant.update(plant_params)
    redirect_to plant_path
  end

  def destroy
    @plant.destroy
    redirect_to plants_path
  end

  private

  def set_task
    @plant = Plant.find(params[:id])
    authorize @plant
  end

  def plant_params
    params.require(:plant).permit(:species, :nickname, :image)
  end
end

app/views/plants/edit.html.erb
<div class="container justify-center">
  <div class="form">
  <div class="d-flex justify-content-center p-4">
    <h2>Update info</h2>
  </div>

  <div class="input">
      <%= simple_form_for (@plant) do |p| %>
      <%= p.input :nickname, placeholder: 'Nickname' %>
      <%= p.input :species, collection: Plant::SPECIES_FILTER %>
      <%= p.input :image, as: :file, required: false %>

      <div class="form-actions">
          <div class="row justify-content-center">
            <div class="col-2 d-flex justify-content-center">
              <%= p.submit 'Create a plant 🌱', class: "button-form" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/plants/index.html.erb
index.html.erb

app/views/plants/new.html.erb
<div class="container justify-center">
  <div class="form">
  <div class="d-flex justify-content-center p-4">
    <h2>New Plant</h2>
  </div>

  <div class="input">
      <%= simple_form_for (@plant) do |p| %>
      <%= p.input :nickname, placeholder: 'Nickname' %>
      <%= p.input :species, collection: Plant::SPECIES_FILTER %>
      <%= p.input :image, as: :file, required: false %>

      <div class="form-actions">
          <div class="row justify-content-center">
            <div class="col-2 d-flex justify-content-center">
              <%= p.submit 'Create a plant 🌱', class: "button-form" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/plants/show.html.erb
<h2 class="mb-4"><strong>Your plant's profile</strong></h2>
<div>
  <% if @plant.image.attached? %>
    <%= cl_image_tag @plant.image.key, class: "show-img" %>
  <% end %>
</div>

<div class="show-main-card d-flex justify-content-between">
      <div class="id">
        <h1><strong> <%= @plant.nickname.capitalize %></strong></h1>
        <h3><%= @plant.species %></h3>
        <h4 style="color: #809C53"><strong>Alive</strong></h4>
      </div>
        <div class="d-flex flex-column align-items-end justify-content-between">
          <div class="p-2">
            <%= link_to edit_plant_path(@plant) do %>
             <i class="far fa-bell big" style="font-size: 1.2rem;"></i>
            <% end %>
          </div>
          <div class="d-flex align-items-end flex-column">
          </div>
      </div>
    </div>

<% this_plant = {}  %>
<%  plant_file = File.read('./app/assets/plantdb/data.json') %>
<%  plants = JSON.parse(plant_file) %>
<% plants["alphabetList"]["glossaryItems"].each do |result| %>
<% this_plant = result if result["primaryName"] == @plant.species %>
<% end %>
<% url = this_plant["url"]  %>
<% plant_description_string = RestClient.get(url).body  %>
<% html_doc = Nokogiri::HTML(plant_description_string)  %>
<% description = html_doc.search('#mntl-sc-block_1-0').text.strip  %>

<div class="row">
  <div class="col-6 nopaddinga">
       <img class="img-breed" src=<%= this_plant["imageUrl"] %> />
  </div>
  <div class="col-6 nopaddingb">
    <div class="breed-card">
      <div class="breed-content"> <%= description %> </div>
    </div>
  </div>
</div>

app/views/plants/update.html.erb
update.html.erb